#!/bin/sh
orig=/usr/bin/$(basename $0)
[ -n "$SOURCE_DATE_EPOCH" ] || exec $orig "$@"
[ "$*" = "" ] && exec $orig "$@"
[ "$*" = "-a" ] && exec "$0" -s -n -r -v -m -p -i -o

function add
{
    [ -z "$o" ] || o+=" "
    o+="$1"
}

o=""
for arg in "$@" ; do
    case "$arg" in
        -n) # nodename
            add "reproducible"
            ;;
        -v) # kernel version
            add "reproducible"
            ;;
        -r)
            t=`$orig $arg|sed -e 's/^\([0-9][0-9]*\.[0-9][0-9]*\).*/\1-reproducible/'`
            add "$t"
            ;;
        *)
            add "`$orig $arg`"
            ;;
    esac
done
echo "$o"
